In [37]:
import pandas as pd

In [38]:
district_data = pd.read_csv('/content/EducationDataPortal_04.07.2023_School Districts (3).csv')
district_data.head(50)

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_current_student_transport,exp_current_food_serv,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name
0,mixed - most recent,200050,Alaska Gateway School District,AK,Tok,Regular local school district,407.0,403.0,93.0,15317000,...,789000,793000,0,179.0,12,180.0,12,69,2240,Southeast Fairbanks Census Area
1,mixed - most recent,200010,Aleutian Region School District,AK,Anchorage,Regular local school district,25.0,26.0,6.0,1882000,...,0,0,0,12.0,24.5,12.0,24.5,Suppressed data,2020,Anchorage Municipality
2,mixed - most recent,200007,Aleutians East Borough School District,AK,Sand Point,Regular local school district,228.0,194.0,23.0,8906000,...,26000,138000,0,122.0,32,122.0,32,75,2013,Aleutians East Borough
3,mixed - most recent,200180,Anchorage School District,AK,Anchorage,Regular local school district,41856.0,50395.0,5411.0,711147000,...,23145000,21625000,441000,23791.0,42,23829.0,39,84,2020,Anchorage Municipality
4,mixed - most recent,200525,Annette Island School District,AK,Metlakatla,Regular local school district,316.0,275.0,63.0,9917000,...,97000,539000,8000,168.0,27,168.0,27,90,2198,Prince of Wales-Hyder Census Area
5,mixed - most recent,200020,Bering Strait School District,AK,Unalakleet,Regular local school district,1839.0,1694.0,502.0,63580000,...,4000,2918000,0,978.0,7,978.0,9,87,2180,Nome Census Area
6,mixed - most recent,200030,Bristol Bay Borough School District,AK,Naknek,Regular local school district,114.0,111.0,18.0,4531000,...,288000,189000,0,53.0,24.5,55.0,24.5,75,2060,Bristol Bay Borough
7,mixed - most recent,200730,Chatham School District,AK,Angoon,Regular local school district,143.0,172.0,38.0,5001000,...,38000,117000,0,72.0,37,87.0,32,75,2105,Hoonah-Angoon Census Area
8,mixed - most recent,200800,Chugach School District,AK,Anchorage,Regular local school district,694.0,57.0,3.0,7816000,...,0,0,0,170.0,37,169.0,17,64,2020,Anchorage Municipality
9,mixed - most recent,200070,Copper River School District,AK,Glennallen,Regular local school district,401.0,462.0,54.0,8801000,...,718000,161000,0,226.0,46,226.0,38,84,2066,Copper River Census Area
10,mixed - most recent,200060,Cordova City School District,AK,Cordova,Regular local school district,292.0,348.0,18.0,7302000,...,130000,417000,0,163.0,52,163.0,47,90,2063,Chugach Census Area
11,mixed - most recent,200090,Craig City School District,AK,Craig,Regular local school district,867.0,228.0,49.0,7880000,...,130000,329000,2000,199.0,42,200.0,32,64,2198,Prince of Wales-Hyder Census Area
12,mixed - most recent,200100,Delta/Greely School District,AK,Delta Junction,Regular local school district,775.0,852.0,122.0,13144000,...,1255000,362000,0,422.0,51,422.0,55,84,2240,Southeast Fairbanks Census Area
13,mixed - most recent,200770,Denali Borough School District,AK,Healy,Regular local school district,1206.0,270.0,19.0,10647000,...,399000,0,0,384.0,55,413.0,42,77,2068,Denali Borough
14,mixed - most recent,200120,Dillingham City School District,AK,Dillingham,Regular local school district,411.0,456.0,105.0,10887000,...,602000,438000,518000,239.0,31,239.0,31,74,2070,Dillingham Census Area
15,mixed - most recent,200600,Fairbanks North Star Borough School District,AK,Fairbanks,Regular local school district,11386.0,16355.0,1361.0,235436000,...,13881000,5666000,0,6858.0,42,6898.0,39,80,2090,Fairbanks North Star Borough
16,mixed - most recent,200130,Galena City School District,AK,Galena,Regular local school district,9366.0,104.0,18.0,33150000,...,80000,1911000,258000,805.0,59,790.0,34,76,2290,Yukon-Koyukuk Census Area
17,mixed - most recent,200270,Haines Borough School District,AK,Haines,Regular local school district,266.0,335.0,47.0,5465000,...,133000,343000,44000,127.0,67,126.0,42,75,2100,Haines Borough
18,mixed - most recent,200300,Hoonah City School District,AK,Hoonah,Regular local school district,135.0,112.0,36.0,4059000,...,0,125000,0,64.0,22,63.0,22,75,2105,Hoonah-Angoon Census Area
19,mixed - most recent,200330,Hydaburg City School District,AK,Hydaburg,Regular local school district,164.0,67.0,29.0,4229000,...,0,129000,17000,43.0,15,43.0,15,75,2198,Prince of Wales-Hyder Census Area
20,mixed - most recent,200520,Iditarod Area School District,AK,McGrath,Regular local school district,325.0,226.0,63.0,9854000,...,49000,441000,0,104.0,12,106.0,7.5,69,2290,Yukon-Koyukuk Census Area
21,mixed - most recent,200210,Juneau Borough School District,AK,Juneau,Regular local school district,4124.0,4987.0,359.0,82452000,...,3200000,2103000,1744000,2452.0,46,2458.0,40,86,2110,Juneau City and Borough
22,mixed - most recent,200360,Kake City School District,AK,Kake,Regular local school district,99.0,93.0,15.0,3771000,...,37000,238000,28000,56.0,54.5,56.0,34.5,75,2198,Prince of Wales-Hyder Census Area
23,mixed - most recent,200005,Kashunamiut School District,AK,Chevak,Regular local school district,332.0,297.0,133.0,9895000,...,1000,529000,267000,173.0,2.5,174.0,2.5,69,2158,Kusilvak Census Area
24,mixed - most recent,200390,Kenai Peninsula Borough School District,AK,Soldotna,Regular local school district,7962.0,9675.0,1276.0,158085000,...,7964000,3737000,54000,4373.0,47,4370.0,41,88,2122,Kenai Peninsula Borough
25,mixed - most recent,200150,Ketchikan Gateway Borough School District,AK,Ketchikan,Regular local school district,2161.0,2283.0,240.0,44325000,...,1655000,1002000,40000,1175.0,46,1172.0,44,82,2130,Ketchikan Gateway Borough
26,mixed - most recent,200450,Klawock City School District,AK,Klawock,Regular local school district,118.0,148.0,36.0,4010000,...,49000,160000,0,56.0,24.5,56.0,15,75,2198,Prince of Wales-Hyder Census Area
27,mixed - most recent,200480,Kodiak Island Borough School District,AK,Kodiak,Regular local school district,2294.0,2375.0,202.0,48772000,...,1920000,1354000,0,1133.0,41,1143.0,40,82,2150,Kodiak Island Borough
28,mixed - most recent,200760,Kuspuk School District,AK,Aniak,Regular local school district,387.0,344.0,126.0,17069000,...,159000,622000,0,194.0,12,194.0,12,69,2050,Bethel Census Area
29,mixed - most recent,200485,Lake and Peninsula Borough School District,AK,King Salmon,Regular local school district,367.0,292.0,72.0,15959000,...,111000,747000,0,175.0,32,175.0,27,75,2060,Bristol Bay Borough
30,mixed - most recent,200001,Lower Kuskokwim School District,AK,Bethel,Regular local school district,4082.0,3781.0,1418.0,142300000,...,819000,4962000,202000,2255.0,6,2262.0,9,55,2050,Bethel Census Area
31,mixed - most recent,200003,Lower Yukon School District,AK,Mountain Village,Regular local school district,2103.0,1858.0,838.0,63340000,...,6000,3085000,0,1065.0,3,1056.0,0.5,67,2158,Kusilvak Census Area
32,mixed - most recent,200510,Matanuska-Susitna Borough School District,AK,Palmer,Regular local school district,18220.0,21179.0,2142.0,282217000,...,17747000,6870000,97000,8542.0,45,8525.0,41,85,2170,Matanuska-Susitna Borough
33,mixed - most recent,200006,Mount Edgecumbe,AK,Sitka,State-operated agency,374.0,NaN,NaN,12510000,...,0,310000,0,111.0,22,111.0,32,97,2220,Sitka City and Borough
34,mixed - most recent,200540,Nenana City School District,AK,Nenana,Regular local school district,1909.0,68.0,14.0,11781000,...,136000,334000,0,243.0,46,247.0,24,42,2290,Yukon-Koyukuk Census Area
35,mixed - most recent,200570,Nome Public Schools,AK,Nome,Regular local school district,691.0,764.0,115.0,13882000,...,525000,764000,22000,401.0,21,400.0,20,74,2180,Nome Census Area
36,mixed - most recent,200610,North Slope Borough School District,AK,Utqiagvik,Regular local school district,2138.0,1825.0,260.0,79934000,...,2617000,3885000,360000,1065.0,12,1046.0,15,77,2185,North Slope Borough
37,mixed - most recent,200625,Northwest Arctic Borough School District,AK,Kotzebue,Regular local school district,2050.0,1926.0,481.0,76569000,...,73000,3425000,0,1102.0,10,1100.0,11,67,2188,Northwest Arctic Borough
38,mixed - most recent,200630,Pelican City School District,AK,Pelican,Regular local school district,11.0,11.0,2.0,613000,...,0,0,0,8.0,24.5,8.0,24.5,Suppressed data,2105,Hoonah-Angoon Census Area
39,mixed - most recent,200660,Petersburg Borough School District,AK,Petersburg,Regular local school district,428.0,477.0,42.0,9590000,...,212000,339000,0,241.0,69,241.0,56,95,2195,Petersburg Borough
40,mixed - most recent,200670,Pribilof School District,AK,St. Paul Island,Regular local school district,65.0,82.0,9.0,2075000,...,0,0,257000,41.0,24.5,41.0,15,Suppressed data,2016,Aleutians West Census Area
41,mixed - most recent,200680,Saint Mary's School District,AK,Saint Mary's,Regular local school district,216.0,148.0,62.0,6237000,...,73000,339000,0,109.0,12,109.0,22,75,2158,Kusilvak Census Area
42,mixed - most recent,200240,Sitka School District,AK,Sitka,Regular local school district,1151.0,1417.0,99.0,24285000,...,601000,542000,1038000,631.0,55,643.0,46,77,2220,Sitka City and Borough
43,mixed - most recent,200690,Skagway School District,AK,Skagway,Regular local school district,144.0,121.0,11.0,3232000,...,4000,147000,0,65.0,87,65.0,77,Suppressed data,2230,Skagway Municipality
44,mixed - most recent,200700,Southeast Island School District,AK,Thorne Bay,Regular local school district,153.0,271.0,31.0,7718000,...,138000,253000,50000,111.0,52,111.0,32,75,2198,Prince of Wales-Hyder Census Area
45,mixed - most recent,200710,Southwest Region School District,AK,Dillingham,Regular local school district,652.0,624.0,211.0,22292000,...,486000,945000,0,337.0,6,336.0,9,74,2070,Dillingham Census Area
46,mixed - most recent,200715,Tanana City School District,AK,Tanana,Regular local school district,30.0,48.0,8.0,1833000,...,47000,35000,0,30.0,30,30.0,10,Suppressed data,2290,Yukon-Koyukuk Census Area
47,mixed - most recent,200720,Unalaska City School District,AK,Unalaska,Regular local school district,387.0,350.0,20.0,9078000,...,280000,428000,879000,223.0,54,223.0,49,95,2016,Aleutians West Census Area
48,mixed - most recent,200780,Valdez City School District,AK,Valdez,Regular local school district,692.0,640.0,96.0,15941000,...,546000,777000,808000,341.0,52,342.0,45,95,2063,Chugach Census Area
49,mixed - most recent,200810,Wrangell Public School District,AK,Wrangell,Regular local school district,181.0,385.0,51.0,6482000,...,272000,66000,0,149.0,52,149.0,57,90,2275,Wrangell City and Borough

In [39]:
district_data.shape

(19507, 27)

In [40]:
district_data = district_data.dropna()
district_data.head(50)

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_current_student_transport,exp_current_food_serv,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name
0,mixed - most recent,200050,Alaska Gateway School District,AK,Tok,Regular local school district,407.0,403.0,93.0,15317000,...,789000,793000,0,179.0,12,180.0,12,69,2240,Southeast Fairbanks Census Area
1,mixed - most recent,200010,Aleutian Region School District,AK,Anchorage,Regular local school district,25.0,26.0,6.0,1882000,...,0,0,0,12.0,24.5,12.0,24.5,Suppressed data,2020,Anchorage Municipality
2,mixed - most recent,200007,Aleutians East Borough School District,AK,Sand Point,Regular local school district,228.0,194.0,23.0,8906000,...,26000,138000,0,122.0,32,122.0,32,75,2013,Aleutians East Borough
3,mixed - most recent,200180,Anchorage School District,AK,Anchorage,Regular local school district,41856.0,50395.0,5411.0,711147000,...,23145000,21625000,441000,23791.0,42,23829.0,39,84,2020,Anchorage Municipality
4,mixed - most recent,200525,Annette Island School District,AK,Metlakatla,Regular local school district,316.0,275.0,63.0,9917000,...,97000,539000,8000,168.0,27,168.0,27,90,2198,Prince of Wales-Hyder Census Area
5,mixed - most recent,200020,Bering Strait School District,AK,Unalakleet,Regular local school district,1839.0,1694.0,502.0,63580000,...,4000,2918000,0,978.0,7,978.0,9,87,2180,Nome Census Area
6,mixed - most recent,200030,Bristol Bay Borough School District,AK,Naknek,Regular local school district,114.0,111.0,18.0,4531000,...,288000,189000,0,53.0,24.5,55.0,24.5,75,2060,Bristol Bay Borough
7,mixed - most recent,200730,Chatham School District,AK,Angoon,Regular local school district,143.0,172.0,38.0,5001000,...,38000,117000,0,72.0,37,87.0,32,75,2105,Hoonah-Angoon Census Area
8,mixed - most recent,200800,Chugach School District,AK,Anchorage,Regular local school district,694.0,57.0,3.0,7816000,...,0,0,0,170.0,37,169.0,17,64,2020,Anchorage Municipality
9,mixed - most recent,200070,Copper River School District,AK,Glennallen,Regular local school district,401.0,462.0,54.0,8801000,...,718000,161000,0,226.0,46,226.0,38,84,2066,Copper River Census Area
10,mixed - most recent,200060,Cordova City School District,AK,Cordova,Regular local school district,292.0,348.0,18.0,7302000,...,130000,417000,0,163.0,52,163.0,47,90,2063,Chugach Census Area
11,mixed - most recent,200090,Craig City School District,AK,Craig,Regular local school district,867.0,228.0,49.0,7880000,...,130000,329000,2000,199.0,42,200.0,32,64,2198,Prince of Wales-Hyder Census Area
12,mixed - most recent,200100,Delta/Greely School District,AK,Delta Junction,Regular local school district,775.0,852.0,122.0,13144000,...,1255000,362000,0,422.0,51,422.0,55,84,2240,Southeast Fairbanks Census Area
13,mixed - most recent,200770,Denali Borough School District,AK,Healy,Regular local school district,1206.0,270.0,19.0,10647000,...,399000,0,0,384.0,55,413.0,42,77,2068,Denali Borough
14,mixed - most recent,200120,Dillingham City School District,AK,Dillingham,Regular local school district,411.0,456.0,105.0,10887000,...,602000,438000,518000,239.0,31,239.0,31,74,2070,Dillingham Census Area
15,mixed - most recent,200600,Fairbanks North Star Borough School District,AK,Fairbanks,Regular local school district,11386.0,16355.0,1361.0,235436000,...,13881000,5666000,0,6858.0,42,6898.0,39,80,2090,Fairbanks North Star Borough
16,mixed - most recent,200130,Galena City School District,AK,Galena,Regular local school district,9366.0,104.0,18.0,33150000,...,80000,1911000,258000,805.0,59,790.0,34,76,2290,Yukon-Koyukuk Census Area
17,mixed - most recent,200270,Haines Borough School District,AK,Haines,Regular local school district,266.0,335.0,47.0,5465000,...,133000,343000,44000,127.0,67,126.0,42,75,2100,Haines Borough
18,mixed - most recent,200300,Hoonah City School District,AK,Hoonah,Regular local school district,135.0,112.0,36.0,4059000,...,0,125000,0,64.0,22,63.0,22,75,2105,Hoonah-Angoon Census Area
19,mixed - most recent,200330,Hydaburg City School District,AK,Hydaburg,Regular local school district,164.0,67.0,29.0,4229000,...,0,129000,17000,43.0,15,43.0,15,75,2198,Prince of Wales-Hyder Census Area
20,mixed - most recent,200520,Iditarod Area School District,AK,McGrath,Regular local school district,325.0,226.0,63.0,9854000,...,49000,441000,0,104.0,12,106.0,7.5,69,2290,Yukon-Koyukuk Census Area
21,mixed - most recent,200210,Juneau Borough School District,AK,Juneau,Regular local school district,4124.0,4987.0,359.0,82452000,...,3200000,2103000,1744000,2452.0,46,2458.0,40,86,2110,Juneau City and Borough
22,mixed - most recent,200360,Kake City School District,AK,Kake,Regular local school district,99.0,93.0,15.0,3771000,...,37000,238000,28000,56.0,54.5,56.0,34.5,75,2198,Prince of Wales-Hyder Census Area
23,mixed - most recent,200005,Kashunamiut School District,AK,Chevak,Regular local school district,332.0,297.0,133.0,9895000,...,1000,529000,267000,173.0,2.5,174.0,2.5,69,2158,Kusilvak Census Area
24,mixed - most recent,200390,Kenai Peninsula Borough School District,AK,Soldotna,Regular local school district,7962.0,9675.0,1276.0,158085000,...,7964000,3737000,54000,4373.0,47,4370.0,41,88,2122,Kenai Peninsula Borough
25,mixed - most recent,200150,Ketchikan Gateway Borough School District,AK,Ketchikan,Regular local school district,2161.0,2283.0,240.0,44325000,...,1655000,1002000,40000,1175.0,46,1172.0,44,82,2130,Ketchikan Gateway Borough
26,mixed - most recent,200450,Klawock City School District,AK,Klawock,Regular local school district,118.0,148.0,36.0,4010000,...,49000,160000,0,56.0,24.5,56.0,15,75,2198,Prince of Wales-Hyder Census Area
27,mixed - most recent,200480,Kodiak Island Borough School District,AK,Kodiak,Regular local school district,2294.0,2375.0,202.0,48772000,...,1920000,1354000,0,1133.0,41,1143.0,40,82,2150,Kodiak Island Borough
28,mixed - most recent,200760,Kuspuk School District,AK,Aniak,Regular local school district,387.0,344.0,126.0,17069000,...,159000,622000,0,194.0,12,194.0,12,69,2050,Bethel Census Area
29,mixed - most recent,200485,Lake and Peninsula Borough School District,AK,King Salmon,Regular local school district,367.0,292.0,72.0,15959000,...,111000,747000,0,175.0,32,175.0,27,75,2060,Bristol Bay Borough
30,mixed - most recent,200001,Lower Kuskokwim School District,AK,Bethel,Regular local school district,4082.0,3781.0,1418.0,142300000,...,819000,4962000,202000,2255.0,6,2262.0,9,55,2050,Bethel Census Area
31,mixed - most recent,200003,Lower Yukon School District,AK,Mountain Village,Regular local school district,2103.0,1858.0,838.0,63340000,...,6000,3085000,0,1065.0,3,1056.0,0.5,67,2158,Kusilvak Census Area
32,mixed - most recent,200510,Matanuska-Susitna Borough School District,AK,Palmer,Regular local school district,18220.0,21179.0,2142.0,282217000,...,17747000,6870000,97000,8542.0,45,8525.0,41,85,2170,Matanuska-Susitna Borough
34,mixed - most recent,200540,Nenana City School District,AK,Nenana,Regular local school district,1909.0,68.0,14.0,11781000,...,136000,334000,0,243.0,46,247.0,24,42,2290,Yukon-Koyukuk Census Area
35,mixed - most recent,200570,Nome Public Schools,AK,Nome,Regular local school district,691.0,764.0,115.0,13882000,...,525000,764000,22000,401.0,21,400.0,20,74,2180,Nome Census Area
36,mixed - most recent,200610,North Slope Borough School District,AK,Utqiagvik,Regular local school district,2138.0,1825.0,260.0,79934000,...,2617000,3885000,360000,1065.0,12,1046.0,15,77,2185,North Slope Borough
37,mixed - most recent,200625,Northwest Arctic Borough School District,AK,Kotzebue,Regular local school district,2050.0,1926.0,481.0,76569000,...,73000,3425000,0,1102.0,10,1100.0,11,67,2188,Northwest Arctic Borough
38,mixed - most recent,200630,Pelican City School District,AK,Pelican,Regular local school district,11.0,11.0,2.0,613000,...,0,0,0,8.0,24.5,8.0,24.5,Suppressed data,2105,Hoonah-Angoon Census Area
39,mixed - most recent,200660,Petersburg Borough School District,AK,Petersburg,Regular local school district,428.0,477.0,42.0,9590000,...,212000,339000,0,241.0,69,241.0,56,95,2195,Petersburg Borough
40,mixed - most recent,200670,Pribilof School District,AK,St. Paul Island,Regular local school district,65.0,82.0,9.0,2075000,...,0,0,257000,41.0,24.5,41.0,15,Suppressed data,2016,Aleutians West Census Area
41,mixed - most recent,200680,Saint Mary's School District,AK,Saint Mary's,Regular local school district,216.0,148.0,62.0,6237000,...,73000,339000,0,109.0,12,109.0,22,75,2158,Kusilvak Census Area
42,mixed - most recent,200240,Sitka School District,AK,Sitka,Regular local school district,1151.0,1417.0,99.0,24285000,...,601000,542000,1038000,631.0,55,643.0,46,77,2220,Sitka City and Borough
43,mixed - most recent,200690,Skagway School District,AK,Skagway,Regular local school district,144.0,121.0,11.0,3232000,...,4000,147000,0,65.0,87,65.0,77,Suppressed data,2230,Skagway Municipality
44,mixed - most recent,200700,Southeast Island School District,AK,Thorne Bay,Regular local school district,153.0,271.0,31.0,7718000,...,138000,253000,50000,111.0,52,111.0,32,75,2198,Prince of Wales-Hyder Census Area
45,mixed - most recent,200710,Southwest Region School District,AK,Dillingham,Regular local school district,652.0,624.0,211.0,22292000,...,486000,945000,0,337.0,6,336.0,9,74,2070,Dillingham Census Area
46,mixed - most recent,200715,Tanana City School District,AK,Tanana,Regular local school district,30.0,48.0,8.0,1833000,...,47000,35000,0,30.0,30,30.0,10,Suppressed data,2290,Yukon-Koyukuk Census Area
47,mixed - most recent,200720,Unalaska City School District,AK,Unalaska,Regular local school district,387.0,350.0,20.0,9078000,...,280000,428000,879000,223.0,54,223.0,49,95,2016,Aleutians West Census Area
48,mixed - most recent,200780,Valdez City School District,AK,Valdez,Regular local school district,692.0,640.0,96.0,15941000,...,546000,777000,808000,341.0,52,342.0,45,95,2063,Chugach Census Area
49,mixed - most recent,200810,Wrangell Public School District,AK,Wrangell,Regular local school district,181.0,385.0,51.0,6482000,...,272000,66000,0,149.0,52,149.0,57,90,2275,Wrangell City and Borough
50,mixed - most recent,200840,Yakutat School District,AK,Yakutat,Regular local school district,93.0,79.0,12.0,2101000,...,0,0,12000,39.0,44.5,40.0,24.5,75,2282,Yakutat City and Borough

In [41]:
district_data.shape

(10141, 27)

In [42]:
for col in district_data.columns:
  district_data = district_data[district_data[col] != 'Missing/not reported']

In [43]:
district_data.shape

(10137, 27)

In [44]:
district_data.head()

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_current_student_transport,exp_current_food_serv,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name
0,mixed - most recent,200050,Alaska Gateway School District,AK,Tok,Regular local school district,407.0,403.0,93.0,15317000,...,789000,793000,0,179.0,12,180.0,12,69,2240,Southeast Fairbanks Census Area
1,mixed - most recent,200010,Aleutian Region School District,AK,Anchorage,Regular local school district,25.0,26.0,6.0,1882000,...,0,0,0,12.0,24.5,12.0,24.5,Suppressed data,2020,Anchorage Municipality
2,mixed - most recent,200007,Aleutians East Borough School District,AK,Sand Point,Regular local school district,228.0,194.0,23.0,8906000,...,26000,138000,0,122.0,32,122.0,32,75,2013,Aleutians East Borough
3,mixed - most recent,200180,Anchorage School District,AK,Anchorage,Regular local school district,41856.0,50395.0,5411.0,711147000,...,23145000,21625000,441000,23791.0,42,23829.0,39,84,2020,Anchorage Municipality
4,mixed - most recent,200525,Annette Island School District,AK,Metlakatla,Regular local school district,316.0,275.0,63.0,9917000,...,97000,539000,8000,168.0,27,168.0,27,90,2198,Prince of Wales-Hyder Census Area

In [45]:
for col in district_data.columns:
  district_data = district_data[district_data[col] != 'Suppressed data']

for col in district_data.columns:
  district_data = district_data[district_data[col] != 'Not applicable']

In [46]:
district_data.shape

(9986, 27)

In [47]:
import numpy as np
district_data['District Student Performance Metric'] = 0.3 * np.array(district_data['read_test_pct_prof_midpt']).astype(np.float) + 0.3 * np.array(district_data['math_test_pct_prof_midpt']).astype(np.float) + 0.4 * np.array(district_data['grad_rate_midpt']).astype(np.float)
district_data.head(10)

<ipython-input-47-b53f55ab47b4>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['District Student Performance Metric'] = 0.3 * np.array(district_data['read_test_pct_prof_midpt']).astype(np.float) + 0.3 * np.array(district_data['math_test_pct_prof_midpt']).astype(np.float) + 0.4 * np.array(district_data['grad_rate_midpt']).astype(np.float)

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_current_food_serv,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name,District Student Performance Metric
0,mixed - most recent,200050,Alaska Gateway School District,AK,Tok,Regular local school district,407.0,403.0,93.0,15317000,...,793000,0,179.0,12,180.0,12,69,2240,Southeast Fairbanks Census Area,34.8
2,mixed - most recent,200007,Aleutians East Borough School District,AK,Sand Point,Regular local school district,228.0,194.0,23.0,8906000,...,138000,0,122.0,32,122.0,32,75,2013,Aleutians East Borough,49.2
3,mixed - most recent,200180,Anchorage School District,AK,Anchorage,Regular local school district,41856.0,50395.0,5411.0,711147000,...,21625000,441000,23791.0,42,23829.0,39,84,2020,Anchorage Municipality,57.9
4,mixed - most recent,200525,Annette Island School District,AK,Metlakatla,Regular local school district,316.0,275.0,63.0,9917000,...,539000,8000,168.0,27,168.0,27,90,2198,Prince of Wales-Hyder Census Area,52.2
5,mixed - most recent,200020,Bering Strait School District,AK,Unalakleet,Regular local school district,1839.0,1694.0,502.0,63580000,...,2918000,0,978.0,7,978.0,9,87,2180,Nome Census Area,39.6
6,mixed - most recent,200030,Bristol Bay Borough School District,AK,Naknek,Regular local school district,114.0,111.0,18.0,4531000,...,189000,0,53.0,24.5,55.0,24.5,75,2060,Bristol Bay Borough,44.7
7,mixed - most recent,200730,Chatham School District,AK,Angoon,Regular local school district,143.0,172.0,38.0,5001000,...,117000,0,72.0,37,87.0,32,75,2105,Hoonah-Angoon Census Area,50.7
8,mixed - most recent,200800,Chugach School District,AK,Anchorage,Regular local school district,694.0,57.0,3.0,7816000,...,0,0,170.0,37,169.0,17,64,2020,Anchorage Municipality,41.8
9,mixed - most recent,200070,Copper River School District,AK,Glennallen,Regular local school district,401.0,462.0,54.0,8801000,...,161000,0,226.0,46,226.0,38,84,2066,Copper River Census Area,58.8
10,mixed - most recent,200060,Cordova City School District,AK,Cordova,Regular local school district,292.0,348.0,18.0,7302000,...,417000,0,163.0,52,163.0,47,90,2063,Chugach Census Area,65.7

In [48]:
district_data['enrollment'] = np.array(district_data['enrollment']).astype(int)

In [49]:
district_data.columns

Index(['year', 'leaid', 'lea_name', 'state_location', 'city_location',
       'agency_type', 'enrollment', 'est_population_5_17',
       'est_population_5_17_poverty', 'exp_current_elsec_total',
       'exp_current_instruction_total', 'exp_current_supp_serve_total',
       'exp_current_sch_admin', 'exp_tech_supplies_services',
       'exp_current_pupils', 'exp_current_instruc_staff',
       'exp_current_general_admin', 'exp_current_student_transport',
       'exp_current_food_serv', 'exp_nonelsec_community_serv',
       'read_test_num_valid', 'read_test_pct_prof_midpt',
       'math_test_num_valid', 'math_test_pct_prof_midpt', 'grad_rate_midpt',
       'county_code', 'county_name', 'District Student Performance Metric'],
      dtype='object')

In [50]:
from scipy.stats.mstats import zscore

x1 = np.divide((np.array(district_data['exp_current_elsec_total']).astype(int)), district_data['enrollment'])
x2 = np.divide((np.array(district_data['exp_current_instruction_total']).astype(int)), district_data['enrollment'])
x3 = np.divide((np.array(district_data['exp_current_supp_serve_total']).astype(int)), district_data['enrollment'])
x4 = np.divide((np.array(district_data['exp_current_sch_admin']).astype(int)), district_data['enrollment'])
x5 = np.divide((np.array(district_data['exp_tech_supplies_services']).astype(int)), district_data['enrollment'])


x6 = np.divide((np.array(district_data['exp_current_pupils']).astype(int)), district_data['enrollment'])
x7 = np.divide((np.array(district_data['exp_current_instruc_staff']).astype(int)), district_data['enrollment'])
x8 = np.divide((np.array(district_data['exp_current_general_admin']).astype(int)), district_data['enrollment'])
x9 = np.divide((np.array(district_data['exp_current_student_transport']).astype(int)), district_data['enrollment'])
#x10 = np.divide((np.array(district_data['exp_current_food_serv']).astype(int)), district_data['enrollment'])
#x11 = np.divide((np.array(district_data['exp_nonelsec_community_serv']).astype(int)), district_data['enrollment'])

In [51]:
x_input = np.stack((x2, x3, x4, x5, x6, x7, x8, x9), axis=1)
x_input

array([[17186.73218673, 18457.002457  ,  1331.6953317 , ...,
         7464.37346437,   739.55773956,  1938.57493857],
       [19030.70175439, 18675.43859649,  2521.92982456, ...,
         6236.84210526,  2482.45614035,   114.03508772],
       [ 9746.20126147,  6727.47037462,  1004.2287844 , ...,
          613.93826453,   120.50840979,   552.96731651],
       ...,
       [15741.07142857, 11464.28571429,  1250.        , ...,
          919.64285714,  2758.92857143,  1571.42857143],
       [10072.07207207,  7122.26512227,   890.6048906 , ...,
         1015.44401544,   423.42342342,   965.25096525],
       [14117.11711712, 11702.7027027 ,  1405.40540541, ...,
         2351.35135135,   972.97297297,   896.3963964 ]])

In [52]:
y_input = np.array(district_data['District Student Performance Metric'])
y_input

array([34.8, 49.2, 57.9, ..., 62.7, 66.6, 54.3])

In [53]:
#district_data.to_excel('cleaned_data.xlsx')

In [54]:
district_data = district_data.sort_values(by=['District Student Performance Metric'], ascending=False)
top_50_district_data = district_data.head(50)

In [55]:
top_50_district_data['total_exp'] = np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float) + np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float) + np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float) + np.array(top_50_district_data['exp_current_general_admin']).astype(np.float) + np.array(top_50_district_data['exp_current_student_transport']).astype(np.float) + np.array(top_50_district_data['exp_current_food_serv']).astype(np.float) + np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float)
top_50_district_data

<ipython-input-55-b4578cb40f87>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['total_exp'] = np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float) + np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float) + np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float) + np.array(top_50_district_data['exp_current_general_admin']).astype(np.float) + np.array(top_50_district_data['exp_current_student_transport']).astype(np.float) + np.array(top_50_district_data['exp_current_food_serv']).astype(np.float) + np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float)
<ipython-input-55-b4578cb40f87>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['total_exp'] = np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float) + np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float) + np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float) + np.array(top_50_district_data['exp_current_general_admin']).astype(np.float) + np.array(top_50_district_data['exp_current_student_transport']).astype(np.float) + np.array(top_50_district_data['exp_current_food_serv']).astype(np.float) + np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float)

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name,District Student Performance Metric,total_exp
14453,mixed - most recent,3904660,Solon City,OH,Solon,Regular local school district,4521,4826.0,319.0,74069000,...,289000,2438.0,94,2359.0,96,96,39035,Cuyahoga County,95.4,13121000.0
13780,mixed - most recent,3904528,Chagrin Falls Exempted Village,OH,Chagrin Falls,Regular local school district,1797,1948.0,71.0,30746000,...,382000,952.0,93,903.0,92,97,39035,Cuyahoga County,94.3,6100000.0
13689,mixed - most recent,3904354,Bay Village City,OH,Bay Village,Regular local school district,2395,2652.0,103.0,35276000,...,677000,1300.0,91,1294.0,92,97,39035,Cuyahoga County,93.7,7564000.0
14195,mixed - most recent,3904431,Mariemont City,OH,Cincinnati,Regular local school district,1612,1823.0,169.0,23696000,...,217000,946.0,92,913.0,91,97,39061,Hamilton County,93.7,5499000.0
14353,mixed - most recent,3904821,Ottawa Hills Local,OH,Toledo,Regular local school district,1035,1002.0,69.0,15523000,...,594000,568.0,92,571.0,91,97,39095,Lucas County,93.7,2858000.0
4463,mixed - most recent,1912510,Gilbert Comm School District,IA,Gilbert,Regular local school district,1589,1350.0,41.0,15797000,...,0,840.0,90,843.0,93,97,19169,Story County,93.7,3139000.0
18243,mixed - most recent,5101290,FALLS CHURCH CITY PBLC SCHS,VA,Falls Church,Regular local school district,2500,2810.0,68.0,50361000,...,1800000,1369.0,91,1594.0,90,98,51610,Falls Church city,93.5,17467000.0
14435,mixed - most recent,3904981,Russia Local,OH,Russia,Regular local school district,409,410.0,14.0,4564000,...,39000,230.0,90,227.0,95,95,39149,Shelby County,93.5,869000.0
14013,mixed - most recent,3904539,Granville Exempted Village,OH,Granville,Regular local school district,2500,2701.0,94.0,31060000,...,239000,1384.0,88,1377.0,91,99,39089,Licking County,93.3,8026000.0
13033,mixed - most recent,3615810,JERICHO UNION FREE SCHOOL DISTRICT,NY,JERICHO,Regular local school district,3153,2808.0,157.0,109784000,...,0,1513.0,88,1573.0,92,98,36059,Nassau County,93.2,19192000.0
14198,mixed - most recent,3910031,Marion Local,OH,Maria Stein,Regular local school district,904,846.0,69.0,9153000,...,0,467.0,88,482.0,93,97,39107,Mercer County,93.1,1768000.0
14429,mixed - most recent,3904470,Rocky River City,OH,Rocky River,Regular local school district,2596,2980.0,203.0,39483000,...,1211000,1467.0,91,1435.0,92,95,39035,Cuyahoga County,92.9,7150000.0
14269,mixed - most recent,3904595,New Bremen Local,OH,New Bremen,Regular local school district,778,927.0,22.0,9192000,...,0,404.0,90,413.0,90,97,39011,Auglaize County,92.8,1936000.0
18394,mixed - most recent,5104080,WISE CO PBLC SCHS,VA,Wise,Regular local school district,5542,5497.0,1615.0,54187000,...,0,3027.0,86,3229.0,94,97,51195,Wise County,92.8,12194000.0
13406,mixed - most recent,3625950,SCARSDALE UNION FREE SCHOOL DISTRICT,NY,SCARSDALE,Regular local school district,4657,4634.0,95.0,142382000,...,288000,2453.0,87,2492.0,90,99,36119,Westchester County,92.7,22232000.0
14175,mixed - most recent,3904428,Madeira City,OH,Cincinnati,Regular local school district,1596,1713.0,68.0,20354000,...,356000,831.0,94,831.0,92,92,39061,Hamilton County,92.6,4212000.0
14674,mixed - most recent,3904514,Wyoming City,OH,Wyoming,Regular local school district,1930,2050.0,126.0,27032000,...,48000,1080.0,89,1060.0,90,97,39061,Hamilton County,92.5,4094000.0
16954,mixed - most recent,4813020,CARROLL ISD,TX,SOUTHLAKE,Regular local school district,8324,8966.0,267.0,81954000,...,77000,4627.0,86,4219.0,90,99,48439,Tarrant County,92.4,13936000.0
18388,mixed - most recent,5103950,WEST POINT PBLC SCHS,VA,West Point,Regular local school district,804,629.0,38.0,10350000,...,0,438.0,92,459.0,93,92,51101,King William County,92.3,2913000.0
3806,mixed - most recent,902700,New Canaan School District,CT,New Canaan,Regular local school district,4219,4908.0,186.0,105485000,...,0,2274.0,90,2281.0,87,98,9001,Fairfield County,92.3,16540000.0
4585,mixed - most recent,1923110,Pleasant Valley Comm School District,IA,Bettendorf,Regular local school district,5331,4053.0,184.0,49048000,...,1000,2657.0,87,2660.0,91,97,19163,Scott County,92.2,11674000.0
14486,mixed - most recent,3904858,St Henry Consolidated Local,OH,Saint Henry,Regular local school district,986,936.0,42.0,9863000,...,0,486.0,86,478.0,92,97,39107,Mercer County,92.2,1581000.0
14046,mixed - most recent,3904849,Highland Local,OH,Medina,Regular local school district,3181,3306.0,142.0,33330000,...,0,1725.0,90,1756.0,88,97,39103,Medina County,92.2,6647000.0
14111,mixed - most recent,3904719,Kenston Local,OH,Chagrin Falls,Regular local school district,2593,3324.0,130.0,38967000,...,216000,1421.0,90,1419.0,89,96,39055,Geauga County,92.1,8978000.0
18396,mixed - most recent,5104150,YORK CO PBLC SCHS,VA,Yorktown,Regular local school district,12330,12365.0,711.0,137534000,...,0,6887.0,88,7723.0,92,95,51199,York County,92.0,36370000.0
2311,mixed - most recent,620130,La Canada Unified,CA,La Canada,Regular local school district,3988,3679.0,146.0,49661000,...,71000,2251.0,89,2256.0,85,99,6037,Los Angeles County,91.8,7384000.0
18326,mixed - most recent,5102980,POQUOSON CITY PBLC SCHS,VA,Poquoson,Regular local school district,2069,2114.0,97.0,23716000,...,0,1133.0,91,1292.0,92,92,51735,Poquoson city,91.7,7138000.0
14245,mixed - most recent,3904594,Minster Local,OH,Minster,Regular local school district,838,854.0,26.0,9465000,...,5000,443.0,87,448.0,92,95,39011,Auglaize County,91.7,1692000.0
14241,mixed - most recent,3904936,Miller City-New Cleveland Local,OH,Miller City,Regular local school district,527,381.0,11.0,5531000,...,19000,270.0,87,267.0,92,95,39137,Putnam County,91.7,1217000.0
4562,mixed - most recent,1920910,North Polk Comm School District,IA,Alleman,Regular local school district,1984,1488.0,34.0,17792000,...,0,938.0,87,938.0,89,97,19153,Polk County,91.6,4259000.0
2795,mixed - most recent,630330,Piedmont City Unified,CA,Piedmont,Regular local school district,2464,2539.0,47.0,45898000,...,0,1350.0,87,1351.0,86,99,6001,Alameda County,91.5,7461000.0
13725,mixed - most recent,3904364,Brecksville-Broadview Heights City,OH,Brecksville,Regular local school district,3640,4483.0,245.0,51035000,...,431000,2054.0,89,2040.0,92,93,39035,Cuyahoga County,91.5,10539000.0
4431,mixed - most recent,1908940,Denver Comm School District,IA,Denver,Regular local school district,939,743.0,43.0,7925000,...,0,414.0,87,415.0,91,95,19017,Bremer County,91.4,1880000.0
14108,mixed - most recent,3904934,Kalida Local,OH,Kalida,Regular local school district,600,670.0,14.0,6813000,...,9000,331.0,89,338.0,89,95,39137,Putnam County,91.4,1479000.0
4523,mixed - most recent,1918540,Maquoketa Valley Comm School District,IA,Delhi,Regular local school district,719,706.0,101.0,7920000,...,0,363.0,91,363.0,87,95,19055,Delaware County,91.4,1845000.0
14343,mixed - most recent,3904676,Olentangy Local,OH,Lewis Center,Regular local school district,22089,19667.0,383.0,246253000,...,127000,11684.0,89,11667.0,89,95,39041,Delaware County,91.4,42414000.0
14460,mixed - most recent,3904836,South Range Local,OH,Canfield,Regular local school district,1176,1220.0,90.0,13259000,...,0,679.0,86,673.0,89,97,39099,Mahoning County,91.3,2910000.0
13690,mixed - most recent,3904355,Beachwood City,OH,Beachwood,Regular local school district,1631,1661.0,114.0,33184000,...,800000,762.0,88,741.0,87,97,39035,Cuyahoga County,91.3,8044000.0
16045,mixed - most recent,4218960,Peters Township SD,PA,McMurray,Regular local school district,3933,4590.0,104.0,56784000,...,4000,2102.0,90,2100.0,82,99,42125,Washington County,91.2,9581000.0
17442,mixed - most recent,4828380,LOVEJOY ISD,TX,ALLEN,Regular local school district,4206,3886.0,80.0,47421000,...,960000,2480.0,82,2146.0,90,99,48085,Collin County,91.2,10917000.0
13969,mixed - most recent,3904978,Fort Loramie Local,OH,Fort Loramie,Regular local school district,739,785.0,26.0,8929000,...,1000,430.0,86,432.0,91,95,39149,Shelby County,91.1,1789000.0
14604,mixed - most recent,3904563,Versailles Exempted Village,OH,Versailles,Regular local school district,1264,1275.0,82.0,15214000,...,0,707.0,84,703.0,90,97,39037,Darke County,91.0,3458000.0
4645,mixed - most recent,1929010,Van Meter Comm School District,IA,Van Meter,Regular local school district,972,809.0,34.0,8168000,...,0,465.0,87,465.0,87,97,19049,Dallas County,91.0,2047000.0
7154,mixed - most recent,2503870,Concord-Carlisle,MA,Concord,Regular local school district,1316,1539.0,30.0,28589000,...,753000,309.0,86,309.0,88,97,25017,Middlesex County,91.0,5369000.0
12054,mixed - most recent,3410200,Millburn Township School District,NJ,Millburn,Regular local school district,4697,5087.0,276.0,99712000,...,18000,2957.0,88,2495.0,83,99,34013,Essex County,90.9,11827000.0
14329,mixed - most recent,3904458,Oakwood City,OH,Dayton,Regular local school district,2005,2173.0,167.0,30075000,...,29000,1072.0,90,1066.0,90,92,39113,Montgomery County,90.8,4184000.0
14084,mixed - most recent,3904543,Indian Hill Exempted Village,OH,Cincinnati,Regular local school district,2160,2732.0,117.0,35815000,...,713000,1133.0,89,1077.0,91,92,39061,Hamilton County,90.8,9033000.0
14074,mixed - most recent,3905002,Hudson City,OH,Hudson,Regular local school district,4571,5348.0,122.0,68153000,...,1820000,2482.0,89,2373.0,91,92,39153,Summit County,90.8,16432000.0
4633,mixed - most recent,1927960,Treynor Comm School District,IA,Treynor,Regular local school district,808,658.0,21.0,7894000,...,0,460.0,90,461.0,86,95,19155,Pottawattamie County,90.8,2306000.0
178,mixed - most recent,102490,Mountain Brook City,AL,Mountain Brook,Regular local school district,4441,4678.0,302.0,61101000,...,284000,2272.0,83,2272.0,89,98,1073,Jefferson County,90.8,10347000.0

In [56]:
top_50_district_data['exp_current_sch_admin'] = np.divide(np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_tech_supplies_services'] = np.divide(np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_current_instruc_staff'] = np.divide(np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_current_general_admin'] = np.divide(np.array(top_50_district_data['exp_current_general_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_current_student_transport'] = np.divide(np.array(top_50_district_data['exp_current_student_transport']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_current_food_serv'] = np.divide(np.array(top_50_district_data['exp_current_food_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
top_50_district_data['exp_nonelsec_community_serv'] = np.divide(np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))

<ipython-input-56-39a139c35c26>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_current_sch_admin'] = np.divide(np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_current_sch_admin'] = np.divide(np.array(top_50_district_data['exp_current_sch_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_tech_supplies_services'] = np.divide(np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_tech_supplies_services'] = np.divide(np.array(top_50_district_data['exp_tech_supplies_services']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_current_instruc_staff'] = np.divide(np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_current_instruc_staff'] = np.divide(np.array(top_50_district_data['exp_current_instruc_staff']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_current_general_admin'] = np.divide(np.array(top_50_district_data['exp_current_general_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_current_general_admin'] = np.divide(np.array(top_50_district_data['exp_current_general_admin']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_current_student_transport'] = np.divide(np.array(top_50_district_data['exp_current_student_transport']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_current_student_transport'] = np.divide(np.array(top_50_district_data['exp_current_student_transport']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_current_food_serv'] = np.divide(np.array(top_50_district_data['exp_current_food_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_current_food_serv'] = np.divide(np.array(top_50_district_data['exp_current_food_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top_50_district_data['exp_nonelsec_community_serv'] = np.divide(np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))
<ipython-input-56-39a139c35c26>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_50_district_data['exp_nonelsec_community_serv'] = np.divide(np.array(top_50_district_data['exp_nonelsec_community_serv']).astype(np.float), np.array(top_50_district_data['total_exp']).astype(np.double))

In [57]:
np.mean(top_50_district_data['exp_current_sch_admin'])

0.25947068660182576

In [58]:
np.mean(top_50_district_data['exp_tech_supplies_services'])

0.08760128597338865

In [59]:
np.mean(top_50_district_data['exp_current_instruc_staff'])

0.19048211844706917

In [60]:
np.mean(top_50_district_data['exp_current_general_admin'])

0.12323958134875093

In [61]:
np.mean(top_50_district_data['exp_current_student_transport'])

0.17925887553510866

In [62]:
np.mean(top_50_district_data['exp_current_food_serv'])

0.129152141904699

In [63]:
np.mean(top_50_district_data['exp_nonelsec_community_serv'])

0.03079531018915789

In [64]:
district_data['total_exp'] = np.array(district_data['exp_current_sch_admin']).astype(np.float) + np.array(district_data['exp_tech_supplies_services']).astype(np.float) + np.array(district_data['exp_current_instruc_staff']).astype(np.float) + np.array(district_data['exp_current_general_admin']).astype(np.float) + np.array(district_data['exp_current_student_transport']).astype(np.float) + np.array(district_data['exp_current_food_serv']).astype(np.float) + np.array(district_data['exp_nonelsec_community_serv']).astype(np.float)
district_data

<ipython-input-64-bcfa38769e5d>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['total_exp'] = np.array(district_data['exp_current_sch_admin']).astype(np.float) + np.array(district_data['exp_tech_supplies_services']).astype(np.float) + np.array(district_data['exp_current_instruc_staff']).astype(np.float) + np.array(district_data['exp_current_general_admin']).astype(np.float) + np.array(district_data['exp_current_student_transport']).astype(np.float) + np.array(district_data['exp_current_food_serv']).astype(np.float) + np.array(district_data['exp_nonelsec_community_serv']).astype(np.float)

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,exp_nonelsec_community_serv,read_test_num_valid,read_test_pct_prof_midpt,math_test_num_valid,math_test_pct_prof_midpt,grad_rate_midpt,county_code,county_name,District Student Performance Metric,total_exp
14453,mixed - most recent,3904660,Solon City,OH,Solon,Regular local school district,4521,4826.0,319.0,74069000,...,289000,2438.0,94,2359.0,96,96,39035,Cuyahoga County,95.40,13121000.0
13780,mixed - most recent,3904528,Chagrin Falls Exempted Village,OH,Chagrin Falls,Regular local school district,1797,1948.0,71.0,30746000,...,382000,952.0,93,903.0,92,97,39035,Cuyahoga County,94.30,6100000.0
13689,mixed - most recent,3904354,Bay Village City,OH,Bay Village,Regular local school district,2395,2652.0,103.0,35276000,...,677000,1300.0,91,1294.0,92,97,39035,Cuyahoga County,93.70,7564000.0
14195,mixed - most recent,3904431,Mariemont City,OH,Cincinnati,Regular local school district,1612,1823.0,169.0,23696000,...,217000,946.0,92,913.0,91,97,39061,Hamilton County,93.70,5499000.0
14353,mixed - most recent,3904821,Ottawa Hills Local,OH,Toledo,Regular local school district,1035,1002.0,69.0,15523000,...,594000,568.0,92,571.0,91,97,39095,Lucas County,93.70,2858000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10268,mixed - most recent,3017040,Lodge Grass H S,MT,Lodge Grass,Regular local school district,187,162.0,60.0,3252000,...,0,17.0,10,17.0,10,24,30003,Big Horn County,15.60,579000.0
16580,mixed - most recent,4652770,Oelrichs School District 23-3,SD,Oelrichs,Regular local school district,128,46.0,5.0,2686000,...,0,64.0,12,64.0,7.5,24,46047,Fall River County,15.45,784000.0
19466,mixed - most recent,5600960,Fremont County School District #38,WY,Arapahoe,Regular local school district,442,422.0,101.0,13308000,...,105000,264.0,14,264.0,5,24,56013,Fremont County,15.30,4726000.0
11291,mixed - most recent,3176400,SANTEE COMMUNITY SCHOOLS,NE,NIOBRARA,Regular local school district,255,156.0,43.0,5985000,...,0,74.0,2.5,74.0,2.5,30,31107,Knox County,13.50,1501000.0
16581,mixed - most recent,4665460,Oglala Lakota County 65-1,SD,Batesland,Regular local school district,1807,3862.0,2017.0,25623000,...,14000,833.0,8,832.0,4,2,46102,Oglala Lakota County,4.40,6982000.0

In [65]:
district_data['exp_current_sch_admin'] = np.divide(np.array(district_data['exp_current_sch_admin']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_tech_supplies_services'] = np.divide(np.array(district_data['exp_tech_supplies_services']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_current_instruc_staff'] = np.divide(np.array(district_data['exp_current_instruc_staff']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_current_general_admin'] = np.divide(np.array(district_data['exp_current_general_admin']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_current_student_transport'] = np.divide(np.array(district_data['exp_current_student_transport']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_current_food_serv'] = np.divide(np.array(district_data['exp_current_food_serv']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
district_data['exp_nonelsec_community_serv'] = np.divide(np.array(district_data['exp_nonelsec_community_serv']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))

<ipython-input-65-b77c1bbbdcd8>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_current_sch_admin'] = np.divide(np.array(district_data['exp_current_sch_admin']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_tech_supplies_services'] = np.divide(np.array(district_data['exp_tech_supplies_services']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_current_instruc_staff'] = np.divide(np.array(district_data['exp_current_instruc_staff']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_current_general_admin'] = np.divide(np.array(district_data['exp_current_general_admin']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_current_student_transport'] = np.divide(np.array(district_data['exp_current_student_transport']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_current_food_serv'] = np.divide(np.array(district_data['exp_current_food_serv']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))
<ipython-input-65-b77c1bbbdcd8>:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  district_data['exp_nonelsec_community_serv'] = np.divide(np.array(district_data['exp_nonelsec_community_serv']).astype(np.float), np.array(district_data['total_exp']).astype(np.double))

In [66]:
optimal_values = np.array([0.25947068660182576, 0.08760128597338865, 0.19048211844706917, 0.12323958134875093, 0.17925887553510866, 0.129152141904699, 0.03079531018915789])

In [67]:
np.sum(optimal_values)

1.0

In [68]:
district_data['optimal_exp_current_sch_admin'] = 0.25947068660182576
district_data['optimal_exp_tech_supplies_services'] = 0.08760128597338865
district_data['optimal_exp_current_instruc_staff'] = 0.19048211844706917
district_data['optimal_exp_current_general_admin'] = 0.12323958134875093
district_data['optimal_exp_current_student_transport'] = 0.17925887553510866
district_data['optimal_exp_current_food_serv'] = 0.129152141904699
district_data['optimal_exp_nonelsec_community_serv'] = 0.03079531018915789

In [69]:
district_data

,year,leaid,lea_name,state_location,city_location,agency_type,enrollment,est_population_5_17,est_population_5_17_poverty,exp_current_elsec_total,...,county_name,District Student Performance Metric,total_exp,optimal_exp_current_sch_admin,optimal_exp_tech_supplies_services,optimal_exp_current_instruc_staff,optimal_exp_current_general_admin,optimal_exp_current_student_transport,optimal_exp_current_food_serv,optimal_exp_nonelsec_community_serv
14453,mixed - most recent,3904660,Solon City,OH,Solon,Regular local school district,4521,4826.0,319.0,74069000,...,Cuyahoga County,95.40,13121000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
13780,mixed - most recent,3904528,Chagrin Falls Exempted Village,OH,Chagrin Falls,Regular local school district,1797,1948.0,71.0,30746000,...,Cuyahoga County,94.30,6100000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
13689,mixed - most recent,3904354,Bay Village City,OH,Bay Village,Regular local school district,2395,2652.0,103.0,35276000,...,Cuyahoga County,93.70,7564000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
14195,mixed - most recent,3904431,Mariemont City,OH,Cincinnati,Regular local school district,1612,1823.0,169.0,23696000,...,Hamilton County,93.70,5499000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
14353,mixed - most recent,3904821,Ottawa Hills Local,OH,Toledo,Regular local school district,1035,1002.0,69.0,15523000,...,Lucas County,93.70,2858000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10268,mixed - most recent,3017040,Lodge Grass H S,MT,Lodge Grass,Regular local school district,187,162.0,60.0,3252000,...,Big Horn County,15.60,579000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
16580,mixed - most recent,4652770,Oelrichs School District 23-3,SD,Oelrichs,Regular local school district,128,46.0,5.0,2686000,...,Fall River County,15.45,784000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
19466,mixed - most recent,5600960,Fremont County School District #38,WY,Arapahoe,Regular local school district,442,422.0,101.0,13308000,...,Fremont County,15.30,4726000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
11291,mixed - most recent,3176400,SANTEE COMMUNITY SCHOOLS,NE,NIOBRARA,Regular local school district,255,156.0,43.0,5985000,...,Knox County,13.50,1501000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795
16581,mixed - most recent,4665460,Oglala Lakota County 65-1,SD,Batesland,Regular local school district,1807,3862.0,2017.0,25623000,...,Oglala Lakota County,4.40,6982000.0,0.259471,0.087601,0.190482,0.12324,0.179259,0.129152,0.030795

In [70]:
district_data.to_excel('cleaned_data.xlsx')